### ISSUE TITLE
Can not run `yarn test`

### ISSUE THREAD

**Issue by zhouzhou84** [counterfactual/contracts#25]
hello

I git clone this Repositories and Run `yarn ganache `in a separate terminal

but when I type `yarn test` ,it gose wrong:
```
ubuntu@ip-172-31-15-69:~/counterfactual$ yarn test
yarn run v1.9.4
$ yarn ganache &> ganache.log & yarn build:pre && yarn build:packages && wsrun test $PKG --exclude-missing && yarn build:post
$ ./bin/prebuild
$ ganache-cli --gasLimit 0xfffffffffff --port 9545 --account="${npm_package_config_unlockedAccount}" -m "${npm_package_config_mnemonic}"
$ wsrun build $PKG --fast-exit -r --serial --exclude-missing
@counterfactual/configs has no  build script, skipping missing
@counterfactual/run-with-ganache has no  build script, skipping missing
@counterfactual/typescript-typings has no  build script, skipping missing
@counterfactual/test-utils
$ tsc --project tsconfig.json.modified
 | error TS5014: Failed to parse file 'packages/test-utils/tsconfig.json.modified/tsconfig.json': Unexpected token u in JSON at position 0.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
`yarn build` failed with exit code 1
Stopping 1 active children
Aborted execution due to previous error
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
ubuntu@ip-172-31-15-69:~/counterfactual$ Ganache CLI v6.1.7 (ganache-core: 2.2.0)
Error: listen EADDRINUSE 127.0.0.1:9545
    at Server.setupListenHandle [as _listen2] (net.js:1336:14)
    at listenInCluster (net.js:1384:12)
    at doListen (net.js:1510:7)
    at process._tickCallback (internal/process/next_tick.js:63:19)
    at Function.Module.runMain (internal/modules/cjs/loader.js:745:11)
    at startup (internal/bootstrap/node.js:266:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:596:3)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

### system configuration
```
ubuntu@ip-172-31-15-69:~/counterfactual$ uname -a 
Linux ip-172-31-15-69 4.4.0-1061-aws #70-Ubuntu SMP Fri May 25 21:47:34 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
ubuntu@ip-172-31-15-69:~/counterfactual$ node -v
v10.8.0
ubuntu@ip-172-31-15-69:~/counterfactual$ nodejs -v
v8.11.3
ubuntu@ip-172-31-15-69:~/counterfactual$ yarn -v
1.9.4
ubuntu@ip-172-31-15-69:~/counterfactual$ 

```

NEED HELP!

**Comment by cf19drofxots** [comment]
@zhouzhou84 I was unable to repro the issue with the same system configuration as you posted.

So the sequence of steps you ran was
1. git clone
2. yarn
3. yarn ganache
4. yarn test

correct?

Seems like this is the offending line is
```
Failed to parse file 'packages/test-utils/tsconfig.json.modified/tsconfig.json'
```
as that's not a valid path.

What do `ls packages/test-utils` and `cat packages/test-utils/package.json` show?

**Comment by cf19drofxots** [comment]
@zhouzhou84 the build scripts have been updated so you shouldn't have problems if you clone and follow the steps again. You can let me know by making an issue if you do run into other problems.
